<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="base_mass" value="5.0" />
    <xacro:property name="wheel_mass" value="1.0" />
    <xacro:property name="caster_wheel_mass" value="0.5" />

    <link name="base_footprint" />
    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="black" />
        </visual>

        <collision>
        	<geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="${base_mass}" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
        				   xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </link>
    
    <joint name="base_joint" type="fixed">
    	<parent link="base_footprint" />
    	<child link="base_link" />
    	<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>
    
    
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="yellow" />
            </visual>

            <collision>
            	<geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>

            <xacro:wheel_inertia m="${wheel_mass}" r="${2*wheel_radius}" l="${2*wheel_length}"
            					 xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>    
        </link>
    </xacro:macro>>

    <xacro:wheel_link prefix="left" />
    
    <joint name="base_left_wheel_joint" type="continuous">
    	<parent link="base_link" />
    	<child link="left_wheel_link" />
    	<origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
    	<axis xyz= "0 1 0" />
    </joint>
    
    <xacro:wheel_link prefix="right" />
    
    <joint name="base_right_wheel_joint" type="continuous">
    	<parent link="base_link" />
    	<child link="right_wheel_link" />
    	<origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
    	<axis xyz= "0 1 0" />
    </joint>
    
    <link name="caster_wheel">
    	<visual>
    		<geometry>
    			<sphere radius="${wheel_radius / 2.0}" />
    			<origin xyz="0 0 0" rpy="0 0 0" />
    			<material name="red" />
    		</geometry>
    	</visual>

    	<collision>
    	    <geometry>
    		    <sphere radius="${wheel_radius / 2.0}" />
    		    <origin xyz="0 0 0" rpy="0 0 0" />
    		</geometry>
    	</collision>

    	<xacro:caster_wheel_inertia m="0.5" r="${wheel_radius / 2.0}" xyz="0 0 0" rpy="0 0 0" />
    </link>
    
    <joint name="base_caster_wheel_joint" type="fixed">
    	<parent link="base_link" />
    	<child link="caster_wheel" />
    	<origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

</robot>